version: '3.7'
services:
  mongo1:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER} # taken from .env file or env-variables
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  app:
    image: thimokoenig/amz-watchlist:latest
    environment:
      MONGO_DB_USER: ${MONGO_DB_USER}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_HOST: mongo1
      MONGO_DB_PORT: 27017
    depends_on:
      - mongo1
    ports:
      - 8080:8080

volumes:
  mongodb_data_container: