version: '3.7'
services:
  mongo1:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER} # taken from .env file or env-variables
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb_data_container:/data/db
  amz-watchlist:
    image: thimokoenig/amz-watchlist:latest
    environment:
      MONGO_DB_USER: ${MONGO_DB_USER}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_HOST: mongo1
      MONGO_DB_PORT: 27017
    depends_on:
      - mongo1
    restart: always
  caddy:
    image: caddy
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mongo1
      - amz-watchlist
    restart: always
    ports:
      - 80:80
      - 443:443
    command: caddy reverse-proxy --from localhost --to amz-watchlist:8080 

volumes:
  mongodb_data_container:
  caddy_data:
  caddy_config: