version: '3.7'
services:
  mongo1:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  app:
    image: thimokoenig/amz-watchlist:latest
    depends_on:
      - mongo1
    ports:
      - 8080:8080

volumes:
  mongodb_data_container: